server:
  port: 8090
  servlet:
    context-path: /community

spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.24.226.87:3306/newkewang?useSSL=false&amp;userUnicode=true&amp;charcterEncoding=UTF-8
    username: root
    password: Aliyun@qq.com
    # hikari connection
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

  redis:
    database: 0
    host: 120.24.226.87
    password: redis888***
    port: 6379

  # MailProperties
  mail:
    host: smtp.sina.com
    port: 465
    username: zhi_oss@sina.cn
    password: 88cfd3c8f7948cfb
    # 发送的协议
    protocol: smtps
    # 使用ssl安全连接
    properties:
      mail.smtp.ssl.enable: true

  servlet:
    multipart:
      # 上传文件最大为10MB
      max-file-size: 10MB

  # kafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      # 组id
      group-id: community-consumer-group
      # 是否自动提交偏移量
      enable-auto-commit: true
      # 自动提交的频率
      auto-commit-interval: 3000

  # ElasticsearchProperties

# mybatis
mybatis:
  # mapper location
  mapper-locations: classpath:mybatis/mapper/*.xml
  # type aliases
  type-aliases-package: com.newkewang.entity
  configuration:
    # 使用生成主键 - 在将数据存储数据库的同时也可以获取到对应的主键信息
    use-generated-keys: true
    # 开启自动映射
    map-underscore-to-camel-case: true

# community
community:
  path:
    # 服务器域名或地址
    domain: http://localhost:8090
    # 上传路径
    upload: e:/data/upload


## lgger
## 设置对应的包的日志等级
#logging.level.com.newkewang: debug
## 设置日志文件存放位置
#logging:
#  file:
#    path: ./log


#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      #druid 数据源专有配置
#      initialSize: 5
#      minIdle: 5
#      maxActive: 15
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
#      #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
#      #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
#      filters: stat,wall,log4j
#      maxPoolPreparedStatementPerConnectionSize: 20
#      useGlobalDataSourceStat: true
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

